apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
      - image: mongo:3-xenial
        name: {{ .Release.Name }}
        args:
          {{- range $key, $value := .Values.volumes }}
          - --dbpath=/home/stackn/{{ $key }}
          {{- end }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.credentials.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.credentials.password }}
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        {{- range $key, $value := .Values.volumes }}
        - name: {{ $key }}
          mountPath: /home/stackn/{{ $value.name }}
        {{- end }}
        # {{- with .Values.extraVolumeMounts }}
        # {{- tpl . $ | nindent 8 }}
        # {{- end }}
      hostname: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      {{- range $key, $value := .Values.volumes }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.claim }}
      {{- end }}
      # {{- with .Values.extraVolumes }}
      # {{- tpl . $ | nindent 6 }}
      # {{- end }}
status: {}
