# version x.x.x corresponds to "latest"
dependencies:
  # - name: openfaas
  #   version: 5.6.5
  #   repository: "https://openfaas.github.io/faas-netes/"
  #   condition: openfaas.enabled

  # - name: argo-events
  #   version: 0.14.0
  #   repository: "https://argoproj.github.io/argo-helm"
  #   condition: argo-events.enabled

  # - name: argo
  #   version: 0.7.3
  #   repository: "https://argoproj.github.io/argo-helm"
  #   condition: argo.enabled

  - name: docker-registry
    version: 1.9.1
    repository: "https://charts.helm.sh/stable"
    condition: docker-registry.enabled
  
  - name: keycloak
    version: 9.9.2
    repository: https://codecentric.github.io/helm-charts

  - name: prometheus
    version: 11.11.1
    repository: https://charts.helm.sh/stable
    condition: prometheus.enabled

  - name: loki-stack
    version: 0.40.0
    repository: https://grafana.github.io/loki/charts
    condition: loki-stack.enabled
  
  - name: grafana
    version: 5.5.5
    repository: https://charts.helm.sh/stable
    condition: grafana.enabled

  - name: postgresql-ha
    version: 6.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgres-ha.enabled