apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-dask-proxy-svc
spec:
  ports:
  - port: {{ .Values.scheduler.port }}
    targetPort: {{ .Values.scheduler.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-dask-scheduler