
namespace: default

global:
  domain: platform.local

ingress:
  secretName: prod-ingress

gatekeeper:
  image: registry.local.stackn.dev/gatekeeper:latest #registry.scilifelab.stackn.dev/keycloak-gatekeeper:latest #keycloak/keycloak-gatekeeper:latest
  realm: STACKn
  client_secret: 75ffdab1-605a-49a9-9544-4807072d0908
  client_id: wetty-test
  auth_endpoint: https://keycloak.local.stackn.dev/auth/realms
  skip_tls: 0
