kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-algo-gk
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  gatekeeper.yaml: |-
    resources:
    - uri: /*
      roles:
      - {{ .Values.gatekeeper.client_id }}:owner
    enable-default-deny: false
    discovery-url: {{ .Values.gatekeeper.auth_endpoint }}/{{ .Values.gatekeeper.realm }}
    client-id: {{ .Values.gatekeeper.client_id }}
    client-secret: {{ .Values.gatekeeper.client_secret }}
    listen: 0.0.0.0:{{ .Values.gatekeeper.port }}
    enable-session-cookies: true
    enable-logging: true
    enable-json-logging: true
    upstream-url: http://localhost:{{ .Values.algorithms.port }}
    enable-authorization-header: true
    add-claims:
      - email
