apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-cplogd

spec:
  ports:
  - port: 80
    targetPort: {{ .Values.gatekeeper.port }}
    protocol: TCP
  selector:
    release: {{ .Release.Name }}
    pod: cplogd